parameter_grids:
  knn:
    k: [1, 3, 5, 7, 9, 11, 15, 21]
    distance: ["euclidean", "manhattan", "chebyshev"]

  decision_tree:
    max_depth: [3, 5, 7, 10, 15, 20, null]
    min_samples_split: [2, 5, 10, 20]
    min_samples_leaf: [1, 2, 5, 10]
    criterion: ["gini", "entropy"]

  random_forest:
    n_trees: [10, 25, 50, 100, 200]
    max_depth: [3, 5, 7, 10, 15, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 5]
    max_features: ["sqrt", "log2", null]

  naive_bayes:
    var_smoothing: [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]

optimization:
  grid_search:
    cv_folds: 5
    scoring: "accuracy"
    n_jobs: -1

  random_search:
    n_iter: 50
    cv_folds: 5
    scoring: "accuracy"
    random_state: 42

  bayesian_optimization:
    n_calls: 30
    n_initial_points: 10
    acquisition_function: "gp_hedge"
    random_state: 42